# Generated by Django 3.1.6 on 2021-03-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
