# Generated by Django 3.1.6 on 2021-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scan', '0002_auto_20210304_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='created',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
